# Generated by Django 4.0.6 on 2022-08-22 11:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_and_reg', '0003_rename_home_addr_doctor_home_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], default='scheduled', max_length=15)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('scheduled_on', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 11, 4, 6, 415474, tzinfo=utc))),
                ('confirmed_on', models.DateTimeField(null=True)),
                ('canceled_on', models.DateTimeField(null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth_and_reg.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth_and_reg.patient')),
            ],
        ),
    ]
