# Generated by Django 4.0.6 on 2022-08-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='canceled_on',
            new_name='cancelled_on',
        ),
    ]
