# Generated by Django 4.0.6 on 2022-08-05 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_reg', '0002_doctor_patient_alter_customuser_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='home_addr',
            new_name='home_address',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='office_addr',
            new_name='office_address',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='home_addr',
            new_name='home_address',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
